create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  division text not null,
  division_bn text,
  district text not null,
  district_bn text,
  thana text not null,
  thana_bn text,
  union_name text,
  union_bn text,
  village_name text,
  village_bn text,
  latitude numeric,
  longitude numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint locations_unique_path unique (division, district, thana, union_name, village_name)
);

create index if not exists locations_division_idx on public.locations (division);
create index if not exists locations_district_idx on public.locations (district);
create index if not exists locations_thana_idx on public.locations (thana);
create index if not exists locations_union_idx on public.locations (union_name);
create index if not exists locations_village_idx on public.locations (village_name);

alter table public.locations enable row level security;

drop policy if exists "Public can read locations" on public.locations;
create policy "Public can read locations"
on public.locations
for select
to anon, authenticated
using (true);

create or replace function public.set_locations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists locations_updated_at on public.locations;
create trigger locations_updated_at
before update on public.locations
for each row
execute function public.set_locations_updated_at();
